[[section-concepts]]
== Cross-cutting Concepts
This section is intended to describe the general ideas, regulations and concepts that apply, either to to the whole system, or to several parts of it.

[domain-concepts]
=== Domain Concepts
****
* Message: piece of text to communicate with other user, expressed in turtle syntax for RDF.
* Pod: user repository, following the SOLID specification. It can be located anywhere, not on a single platform.
* Client: the de_chat program running on the user's browser. Its responsability is to give the functionality, not to store the data. 
****

[ux]
=== User Experience
One of the keypoint of the application. The user should not notice any difference from using other chats, like Facebook or WhatsApp.
There two main reasons for this:
* Facilitate the migration from other chat systems easy for any kind of user.
* Prove that it is posible to have the very same services that we currently enjoy using the SOLID system

[arch_patterns]
===Architecture and design patterns
Up until know, the de_chat is an Angular-based system, therefore following the Model View Controller architectural pattern.
However, all our application would not store any of the user's data. It will access it via SOLID pods.

[pers]
=== Persistency
On the current stage of the project, persistency is secondary, although it will supported in the future. All users' data will be avaliable in their pods 

[session]
=== Session handling
No session handling is implemented whatsoever, as the information is ultimately retrieved from the pods themselves.

[Communication]
=== Communication
Two chats would not communicate directly. I will occur via SOLID pods, which are the ones storing the messages.

[test]
=== Testing
No proper testing is currently being performed.

[build]
=== Building
The building of the project, considering that it is an Angular application, is done via the Node.js package manages, *npm*.
*TO-DO*