[[section-technical-risks]]
== Risks and Technical Debts

When we are talking about technical concepts, usually, we are defining a mature system or technology.
This is not the case of our decentralised chat, we are dealing with some experimental our unfinished projects:

*SOLID: Solid is a platform in continous change and evolving everyday, this makes developing our application
quite difficult, we have to manage many concepts and changes quite fast.

*JavaScript: A web language in which we are not native, most of our group is Java native,we had to
use JavaScript in order to optimize our compatibility with most of the code available in the SOLID platform.

*Rdf: Another technology we did not know until we arrived at this project.

*Turtle: A container for RDF data, this allows to focus only on turtle leaving some concepts of rdf forgotten.

*Angular: Web framework written in TypeSrpit another language that we have not used before this project.

As we can conclude this project requires many technologies working alltogether to 
create this chat.