[[section-project-structure]]
== Project Structure



[role="arc42help"]
****
* *a_docs/:* Source AsciiDoc files for the documentation
** images/
** _n_title.adoc_
* *coverage/:* Files generated by the coverage report
* *docs/:* Files generated by the gitbook deploy
* *e2e/:* Source files for the cucumber e2e tests
** src/
*** features/
*** pages/
*** steps/
** _protractor.conf.js:_ Protractor runner configuration
** _tsconfig.e2e.json:_ Typescript compiler configuration (extends the root _tsconfig.json_)
* *node_modules/:* All the dependencies (ignored in the repository)
* *certs/:* Certificates and keys for the HTTPS dev server
* *src/:* Source of the app
** *app/:*
*** *components/:* All the components that make up the app
**** *name/:* Each component has a folder for its files
***** _name.component.css:_ CSS styles for the component, only applied to this component individually
***** _name.component.html:_ HTML code for the component, to be inserted when the component's tag is found
***** _name.component.spec.ts:_ Unit testing code for the component
***** _name.component.ts:_ Main component code
*** *models/:*
**** _chat-message.model.ts:_ Chat message model
**** _notification.model.ts:_ Notification model
**** _solid-profile.model.ts:_ Profile model
**** _solid-provider.model.ts:_ Provider model
**** _solid-session.model.ts:_ Session model
**** _user.model.ts:_ User model
*** *services/:*
**** _auth.guard.service.ts:_ Service in charge of gate-keeping for the routes of the app
**** _chat.service.ts:_ Service in charge of the high-level chat operations
**** _rdf.service.ts:_ Service in charge of the low level rdf operations, called by the chat service
**** _solid.auth.service.ts:_ Service in charge of logging in and out of the app be it by IDP or popup 
*** _app.component.*:_ Component structure for the root component with .ts .html .css and .spec.ts files
*** _app.module.ts:_ Defines the root module, all the components and services are declared here so the framework knows where is what
*** _popup.html:_ HTML Solid login popup
** *assets/:* Contains the resources that should be treated as static when building the app
** *environments/:* Build configurations for different environments (for example: production vs development)
** _browserslist:_ Used to take into account different browsers when building supported/unsupported css
** _favicon.ico:_ The icon of the app to be displayed on the browser tab
** _index.html:_ The main html file where the app-root will be inserted
** _karma.conf.js:_ Configuration of the karma runner for unit tests
** _main.ts:_ Main entry point, it will 'prepare' the AppComponent to run in the browser compiling with the JIT compiler
** _polyfills.ts:_ Provides the browser-specific scripts for support of certain functions
** _styles.css:_ Base styles of the application, its extension determines the styles used in the project
** _test.ts:_ Main entry point for the tests, similar to the _main.ts_ file but initializing the Test Bed
** _tsconfig.app.json:_ Typescript compiler configuration for the app (extends the root _tsconfig.json_)
** _tsconfig.spec.json:_ Typescript compiler configuration for test files (extends the root _tsconfig.json_)
** _tslint.json:_ Typescript linter (TSLint) configuration for the app (extends from the root _tslint.json_)
* *certificates/:* Folder containing the self-signed certificates for https 
* _.gitignore:_ Specifies the untracked files for git (won't be considered when commiting) 
* _travis.yml:_ Travis CLI config file, specifies the steps to take for each commit and pull request in travis
* _angular.json:_ Angular CLI configuration and options for the tools defined by the CLI such as serve, build and test
* _Dockerfile:_ Specifications for the generation of the docker container
* _LICENSE:_ License for the project (currently MIT)
* _package-lock.json:_ The full dependency tree of the project
* _package.json:_ Dependencies both normal and development ones. Also custom commands for serving docs etc
* _patch.js_
* _popup.js:_ Code for the solid login popup
* _README.md:_ README file for the project
* _tsconfig.json:_ Typescript compiler configuration for the whole workspace
* _tslint.json:_ Typescript linter (TSLint) configuration for the whole workspace

****

