== Using the app

Here, you will be given the necessary instructions to use the various functionalities of the app.

=== Loging in 
To use DE_CHAT you need to have an account on a SOLID provider. You will be given the option to select from the various providers, and the either logging in to an existing account, or creating a new one.

**TODO:** add the image of the login

== Seeing my profile
There is a _Profile_ option. There you will be prompted with the following screen:

**TODO:** add the screen shot

Here, you can configure some options of your SOLID profile. From up-down, left to right:

. Your name.
. Your profession
. Your organization
. Your phone number
. Your email address
. Your address

Plus, you can also add new friends by writing their SOLID web id's in the panel below, and then clicking the _Add Friend_ button.

You can return to the chat using the _Chat_ option on the top left corner.

== Seeing my friends

== Selecting an existing chat

== Deleting messages

== Creating new chats

